In [1]:
!pip install faiss-cpu
!pip install sentence-transformers

   ---------------------------------------- 0.0/14.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.5 MB 129.6 kB/s eta 0:01:52
   ---------------------------------------- 0.0/14.5 MB 129.6 kB/s eta 0:01:52
   ---------------------------------------- 0.0/14.5 MB 108.9 kB/s eta 0:02:13
   ---------------------------------------- 0.0/14.5 MB 108.9 kB/s eta 0:02:13
   ---------------------------------------- 0.0/14.5 MB 122.9 kB/s eta 0:01:58
   ---------------------------------------- 0.1/14.5 MB 217.9 kB/s eta 0:01:07
   ---------------------------------------- 0.1/14.5 MB 273.1 kB/s eta 0:00:53
   ---------------------------------------- 0.1/14.5 MB 288.1 kB/s eta 0:00:50
   ---------------------------------------- 0.2/14.5 MB 350.7 kB/s eta 0:00:41
    --------------------------------------- 0.2/14.5 MB 416.7 kB/s eta 0:00:35
    --------------------------------------- 0.3/14.5 MB 449.3 kB/s eta

     ---------------------------------------- 0.0/43.8 kB ? eta -:--:--
     ---------------------------------------- 0.0/43.8 kB ? eta -:--:--
     --------- ------------------------------ 10.2/43.8 kB ? eta -:--:--
     ----------------- -------------------- 20.5/43.8 kB 131.3 kB/s eta 0:00:01
     ----------------- -------------------- 20.5/43.8 kB 131.3 kB/s eta 0:00:01
     ----------------------------------- -- 41.0/43.8 kB 178.6 kB/s eta 0:00:01
     -------------------------------------- 43.8/43.8 kB 179.6 kB/s eta 0:00:00
   ---------------------------------------- 0.0/227.1 kB ? eta -:--:--
   ------- ------------------------------- 41.0/227.1 kB 991.0 kB/s eta 0:00:01
   ---------- ---------------------------- 61.4/227.1 kB 656.4 kB/s eta 0:00:01
   --------------- ----------------------- 92.2/227.1 kB 751.6 kB/s eta 0:00:01
   --------------- ----------------------- 92.2/227.1 kB 751.6 kB/s eta 0:00:01
   ---------------------------------------  225.3/227.1 kB 1.1 MB/s eta 

In [2]:
import pandas as pd

pd.set_option('display.max_colwidth', 100)

In [3]:
df = pd.read_csv('sample_text.csv')
df.shape

(8, 2)

In [4]:
df

text  \
0                                        Meditation and yoga can improve mental health   
1                     Fruits, whole grains and vegetables helps control blood pressure   
2                                    These are the latest fashion trends for this week   
3                                    Vibrant color jeans for male are becoming a trend   
4                                                   The concert starts at 7 PM tonight   
5                      Navaratri dandiya program at Expo center in Mumbai this october   
6                                    Exciting vacation destinations for your next trip   
7  Maldives and Srilanka are gaining popularity in terms of low budget vacation places   

  category  
0   Health  
1   Health  
2  Fashion  
3  Fashion  
4    Event  
5    Event  
6   Travel  
7   Travel

In [5]:
## Converting the sentences into vectors

from sentence_transformers import SentenceTransformer

encoder = SentenceTransformer("all-mpnet-base-v2") ## using all mpnet entity
vectors = encoder.encode(df.text)
vectors.shape

D:\anaconda3\Lib\site-packages\sentence_transformers\cross_encoder\CrossEncoder.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

D:\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:157: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Ian Marx\.cache\huggingface\hub\models--sentence-transformers--all-mpnet-base-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

D:\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

(8, 768)

In [6]:
vectors

array([[-0.00247396,  0.03626723, -0.05290459, ..., -0.09152357,
        -0.03970001, -0.04330489],
       [-0.03357268,  0.00980517, -0.03250129, ..., -0.05165466,
         0.02245888, -0.03156181],
       [-0.01865322, -0.04051315, -0.01235386, ...,  0.00610586,
        -0.07179644,  0.02773852],
       ...,
       [-0.00066459,  0.04252128, -0.05645508, ...,  0.01315471,
        -0.03183568, -0.04357662],
       [-0.03317154,  0.03252454, -0.02484838, ...,  0.0117442 ,
         0.05747125,  0.00571021],
       [-0.00166395,  0.00413827, -0.04597083, ...,  0.02008528,
         0.05656242, -0.00161596]], dtype=float32)

In [10]:
dim = vectors.shape[1]
dim

768

In [12]:
import faiss

##Creating an index that will allow to do faster search

index = faiss.IndexFlatL2(dim) ##IndexFlatL2 is the index that uses eucledian distance or L2 distance
index ## Just creates an empty index

<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x000002360FE6E130> >

In [13]:
## Adding some vectors in that empty faiss index

index.add(vectors)

In [25]:
## Giving an input search query

search_query="I want to buy a neck tie"

vec = encoder.encode(search_query)
vec.shape ##Gives size 768 but expects a 2d array

(768,)

In [26]:
vec

array([ 4.62351330e-02,  3.07513736e-02, -6.88836968e-04,  7.80840055e-04,
       -2.63743270e-02, -3.37427780e-02,  2.93383002e-02,  2.19918299e-03,
        8.66771117e-02,  4.44397442e-02,  2.57255062e-02,  3.56917121e-02,
        3.42323035e-02, -1.16764233e-02,  1.62118324e-03, -3.06000486e-02,
       -5.98554790e-04,  1.80933438e-02,  8.42756405e-02, -3.09394719e-03,
        3.09027266e-02,  5.65517172e-02, -3.84572446e-02, -2.52207421e-04,
       -5.95750213e-02, -2.79485658e-02, -6.88557373e-03,  1.23163760e-02,
        3.87493498e-03, -4.43713479e-02,  6.25550598e-02, -2.53758095e-02,
       -3.78823020e-02, -3.64624336e-02,  1.14790691e-06, -4.02558856e-02,
        2.75033228e-02, -4.51705568e-02, -4.38511707e-02, -3.03249676e-02,
       -2.91058104e-02,  3.33324224e-02, -1.94074605e-02,  8.66387412e-03,
        2.20318120e-02, -1.15481587e-02,  2.56206058e-02,  6.47875369e-02,
       -4.59679812e-02, -2.88765263e-02, -3.67402993e-02,  1.46362698e-03,
       -1.15363405e-03, -

In [27]:
import numpy as np
svec = np.array(vec).reshape(1,-1)
svec.shape

(1, 768)

In [28]:
svec

array([[ 4.62351330e-02,  3.07513736e-02, -6.88836968e-04,
         7.80840055e-04, -2.63743270e-02, -3.37427780e-02,
         2.93383002e-02,  2.19918299e-03,  8.66771117e-02,
         4.44397442e-02,  2.57255062e-02,  3.56917121e-02,
         3.42323035e-02, -1.16764233e-02,  1.62118324e-03,
        -3.06000486e-02, -5.98554790e-04,  1.80933438e-02,
         8.42756405e-02, -3.09394719e-03,  3.09027266e-02,
         5.65517172e-02, -3.84572446e-02, -2.52207421e-04,
        -5.95750213e-02, -2.79485658e-02, -6.88557373e-03,
         1.23163760e-02,  3.87493498e-03, -4.43713479e-02,
         6.25550598e-02, -2.53758095e-02, -3.78823020e-02,
        -3.64624336e-02,  1.14790691e-06, -4.02558856e-02,
         2.75033228e-02, -4.51705568e-02, -4.38511707e-02,
        -3.03249676e-02, -2.91058104e-02,  3.33324224e-02,
        -1.94074605e-02,  8.66387412e-03,  2.20318120e-02,
        -1.15481587e-02,  2.56206058e-02,  6.47875369e-02,
        -4.59679812e-02, -2.88765263e-02, -3.67402993e-0

In [29]:
distances, I = index.search(svec, k=2) # 2 similar vectors, 
## it returns a tuple, one is the distances, 
## the second one is the index in our original df 

In [30]:
I

array([[2, 3]], dtype=int64)

In [31]:
df.loc[(I[0])]

text category
2  These are the latest fashion trends for this week  Fashion
3  Vibrant color jeans for male are becoming a trend  Fashion

In [ ]:
## Once you've stored all your vectors in the vector db 
## The next step will be asking the question are retrieving
## all the relevant chunks e.g chunk 2 and 4.
## Using these chunks I'll form an LLM prompt